"""Eliminar tabla Paciente

Revision ID: 1db273410c11
Revises: 469090ee51ab
Create Date: 2024-01-18 13:55:03.825318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1db273410c11'
down_revision = '469090ee51ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente_nino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relacion_peso_estatura', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('OCUPADO', 'EN_ESPERA'),
               type_=sa.Enum('ocupado', 'en espera'),
               existing_nullable=False)

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_paciente', sa.String(length=20), nullable=False))
        batch_op.drop_column('relacion_peso_estatura')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relacion_peso_estatura', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('tipo_paciente')

    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.Enum('ocupado', 'en espera'),
               type_=mysql.ENUM('OCUPADO', 'EN_ESPERA'),
               existing_nullable=False)

    op.drop_table('paciente_nino')
    # ### end Alembic commands ###
