"""empty message

Revision ID: 29512eccde96
Revises: ffda87c395af
Create Date: 2024-01-18 10:22:20.628244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29512eccde96'
down_revision = 'ffda87c395af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relacion_peso_estatura', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('prioridad', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('riesgo', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('riesgo')
        batch_op.drop_column('prioridad')
        batch_op.drop_column('relacion_peso_estatura')

    # ### end Alembic commands ###
