"""empty message

Revision ID: 2fbb1a898a5e
Revises: 382b30d6b2b1
Create Date: 2024-01-18 14:18:09.445026

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2fbb1a898a5e'
down_revision = '382b30d6b2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente_joven', schema=None) as batch_op:
        batch_op.alter_column('fumador',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente_joven', schema=None) as batch_op:
        batch_op.alter_column('fumador',
               existing_type=sa.String(length=3),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
