"""empty message

Revision ID: 382b30d6b2b1
Revises: bdcb998866de
Create Date: 2024-01-18 14:15:41.037081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382b30d6b2b1'
down_revision = 'bdcb998866de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_paciente', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('tipo_paciente')

    # ### end Alembic commands ###
