"""empty message

Revision ID: 469090ee51ab
Revises: 29512eccde96
Create Date: 2024-01-18 12:01:35.698224

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '469090ee51ab'
down_revision = '29512eccde96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente_nino')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente_nino',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('peso', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estatura', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['paciente.id'], name='paciente_nino_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
