"""empty message

Revision ID: 574edc4d2ea7
Revises: fa1a880cf665
Create Date: 2024-01-18 18:19:13.684855

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '574edc4d2ea7'
down_revision = 'fa1a880cf665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('tipo_consulta',
               existing_type=mysql.ENUM('PEDAITRIA', 'URGENCIA', 'CGI'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('estado',
               existing_type=mysql.ENUM('OCUPADO', 'EN_ESPERA'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consulta', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('OCUPADO', 'EN_ESPERA'),
               existing_nullable=False)
        batch_op.alter_column('tipo_consulta',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PEDAITRIA', 'URGENCIA', 'CGI'),
               existing_nullable=False)

    # ### end Alembic commands ###
