"""empty message

Revision ID: d57db92e3a1f
Revises: 2fbb1a898a5e
Create Date: 2024-01-18 14:20:13.917550

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd57db92e3a1f'
down_revision = '2fbb1a898a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente_anciano', schema=None) as batch_op:
        batch_op.alter_column('tiene_dieta',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=3),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente_anciano', schema=None) as batch_op:
        batch_op.alter_column('tiene_dieta',
               existing_type=sa.String(length=3),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)

    # ### end Alembic commands ###
