"""empty message

Revision ID: ffda87c395af
Revises: 
Create Date: 2024-01-17 10:27:46.749744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffda87c395af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=False),
    sa.Column('no_historia_clinica', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('id_hospital', sa.Integer(), nullable=True),
    sa.Column('cant_pacientes', sa.Integer(), nullable=False),
    sa.Column('nombre_especialista', sa.String(length=50), nullable=False),
    sa.Column('tipo_consulta', sa.Enum('PEDIATRIA', 'URGENCIA', 'CGI', name='tipoconsultaenum'), nullable=False),
    sa.Column('estado', sa.Enum('OCUPADO', 'EN_ESPERA', name='estadoenum'), nullable=False),
    sa.ForeignKeyConstraint(['id_hospital'], ['hospital.id_hospital'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    op.create_table('paciente_anciano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiene_dieta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente_joven',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fumador', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paciente_nino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('estatura', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paciente_nino')
    op.drop_table('paciente_joven')
    op.drop_table('paciente_anciano')
    op.drop_table('consulta')
    op.drop_table('paciente')
    op.drop_table('hospital')
    # ### end Alembic commands ###
